export const bandsList = [
  { name: "Royel Otis", website: "https://www.royelotis.com" },
  { name: "The Belair Lip Bombs", website: "https://thebelairlipbombs.bandcamp.com" },
  { name: "South Summit", website: "https://southsummitband.com" },
  { name: "Katanak", website: "https://katanakmusic.com" },
  { name: "Hockey Dad", website: "https://hockeydadband.com" },
  { name: "Spacey Jane", website: "https://spaceyjane.com.au" },
  { name: "The Jungle Giants", website: "https://thejunglegiants.com" },
  { name: "San Cisco", website: "https://sancisco.com" },
  { name: "Ball Park Music", website: "https://ballparkmusic.com" },
  { name: "Cub Sport", website: "https://cubsport.com" },
  { name: "Middle Kids", website: "https://middlekidsmusic.com" },
  { name: "DMA's", website: "https://dmasmusic.com" },
  { name: "Gang of Youths", website: "https://gangofyouths.com" },
  { name: "The Teskey Brothers", website: "https://theteskeybrothers.com" },
  { name: "Tame Impala", website: "https://tameimpala.com" },
  { name: "King Gizzard & The Lizard Wizard", website: "https://kinggizzardandthelizardwizard.com" },
  { name: "The Rubens", website: "https://therubensmusic.com" },
  { name: "Boy & Bear", website: "https://boyandbear.com" },
  { name: "Amyl and The Sniffers", website: "https://amylandthesniffers.com" },
  { name: "Sticky Fingers", website: "https://stickyfingerstheband.com" },
  { name: "The Cat Empire", website: "https://thecatempire.com" },
  { name: "The Paper Kites", website: "https://thepaperkites.com.au" },
  { name: "Lime Cordiale", website: "https://limecordiale.com" },
  { name: "Ocean Alley", website: "https://oceanalley.com.au" },
  { name: "Parkway Drive", website: "https://parkwaydriverock.com" },
  { name: "The Avalanches", website: "https://theavalanches.com" },
  { name: "RÜFÜS DU SOL", website: "https://rufusdusol.com" },
  { name: "Confidence Man", website: "https://confidenceman.com" },
  { name: "Sheppard", website: "https://wearesheppard.com" },
  { name: "Killing Heidi", website: "https://killingheidi.com" },
  { name: "Baker Boy", website: "https://bakerboymusic.com" },
  { name: "Angie McMahon", website: "https://angiemcmahon.com" },
  { name: "Montaigne", website: "https://montaignemusic.com" },
  { name: "The Grates", website: "https://thegrates.com" },
  { name: "The Getaway Plan", website: "https://thegetawayplan.com" },
  { name: "The Preatures", website: "https://thepreatures.com.au" },
  { name: "Closure in Moscow", website: "https://closureinmoscow.com" },
  { name: "Tonight Alive", website: "https://tonightalive.com" },
  { name: "The Vines", website: "https://thevines.com" },
  { name: "The Temper Trap", website: "https://thetempertrap.com" },
  { name: "The Jezabels", website: "https://thejezabels.com" },
  { name: "Something for Kate", website: "https://somethingforkate.com" },
  { name: "Eskimo Joe", website: "https://eskimojoe.net" },
  { name: "The Drones", website: "https://thedrones.com.au" },
  { name: "Augie March", website: "https://augiemarch.com" },
  { name: "The Waifs", website: "https://thewaifs.com" },
  { name: "The Whitlams", website: "https://thewhitlams.com" },
  { name: "You Am I", website: "https://youami.com.au" },
  { name: "Regurgitator", website: "https://regurgitator.net" },
  { name: "Spiderbait", website: "https://spiderbait.net.au" },
  { name: "Magic Dirt", website: "https://magicdirt.net" },
  { name: "The Living End", website: "https://thelivingend.com.au" },
  { name: "Jebediah", website: "https://jebediah.net" },
  { name: "WAAX", website: "https://waax.bandcamp.com" },
  { name: "DZ Deathrays", website: "https://dzdeathrays.com" },
  { name: "Alex Lahey", website: "https://alexlahey.com" },
  { name: "Tropical Fuck Storm", website: "https://tropicalfstorm.bandcamp.com" },
  { name: "Camp Cope", website: "https://campcope.bandcamp.com" },
  { name: "Pond", website: "https://pondband.net" },
  { name: "Slum Sociable", website: "https://slumsociable.bandcamp.com" },
  { name: "Big Scary", website: "https://bigscary.bandcamp.com" },
  { name: "Holy Holy", website: "https://holyholymusic.com" },
  { name: "Clowns", website: "https://clownsband.com" },
  { name: "Bad//Dreems", website: "https://baddreems.bandcamp.com" },
  { name: "Press Club", website: "https://pressclub.bandcamp.com" },
  { name: "All Our Exes Live in Texas", website: "https://allourexesliveintexas.bandcamp.com" },
  { name: "Middle Kids", website: "https://middlekidsmusic.com" },
  { name: "Sampa The Great", website: "https://sampathegreat.bandcamp.com" },
  { name: "Moaning Lisa", website: "https://moaninglisa.bandcamp.com" },
  { name: "Odette", website: "https://odettesodyssey.com" },
  { name: "Ceres", website: "https://ceresband.com" },
  { name: "Sweater Curse", website: "https://sweatercurse.bandcamp.com" },
  { name: "Stella Donnelly", website: "https://stelladonnelly.bandcamp.com" },
  { name: "Gordi", website: "https://gordi.bandcamp.com" },
  { name: "Jack River", website: "https://jackrivermusic.com" },
  { name: "Hatchie", website: "https://hatchie.net" },
  { name: "Cub Calloway", website: "https://cubcalloway.bandcamp.com" },
  { name: "Dune Rats", website: "https://dunerats.tv" },
  { name: "Rolling Blackouts Coastal Fever", website: "https://rollingblackoutsband.com" },
  { name: "Goon Sax", website: "https://goonsax.bandcamp.com" },
  { name: "Violent Soho", website: "https://violentsoho.com" },
  { name: "The Chats", website: "https://thechatslovebeer.com" },
  { name: "Jungle Giants", website: "https://thejunglegiants.com" },
  { name: "San Mei", website: "https://sanmeimusic.com" },
  { name: "Ecca Vandal", website: "https://eccavandal.com" },
  { name: "Northlane", website: "https://northlaneband.com" },
  { name: "In Hearts Wake", website: "https://inheartswake.com" },
  { name: "Polaris", website: "https://polarisaus.com" },
  { name: "Dream On Dreamer", website: "https://dreamondreamerband.com" },
  { name: "Ocean Grove", website: "https://oceangrove.com" },
  { name: "Tired Lion", website: "https://tiredlion.band" },
  { name: "Dear Seattle", website: "https://dearseattle.com" },
  { name: "RedHook", website: "https://redhookofficial.com" },
  { name: "Kingswood", website: "https://kingswoodband.com" },
  { name: "Thy Art Is Murder", website: "https://thyartismurder.net" },
  { name: "Hacktivist", website: "https://hacktivist.com" },
  { name: "Plague Vendor", website: "https://plaguevendor.bandcamp.com" },
  { name: "Psycroptic", website: "https://psycroptic.com" },
  { name: "Disentomb", website: "https://disentomb.bandcamp.com" },
  { name: "Justice For The Damned", website: "https://justiceforthedamned.com" },
  { name: "Aversions Crown", website: "https://aversionscrown.com" },
  { name: "Alpha Wolf", website: "https://alphawolf.com.au" },
  { name: "Make Them Suffer", website: "https://makethemsuffer.com.au" },
  { name: "Parkway Drive", website: "https://parkwaydriverock.com" },
  { name: "Northlane", website: "https://northlaneband.com" },
  { name: "Polaris", website: "https://polarisaus.com" },
  { name: "Windwaker", website: "https://windwakerband.com" },
  { name: "Hands Like Houses", website: "https://handslikehouses.net" },
  { name: "In Hearts Wake", website: "https://inheartswake.com" },
  { name: "Dream State", website: "https://dreamstateuk.com" },
  { name: "Redhook", website: "https://redhookofficial.com" },
  { name: "Dear Seattle", website: "https://dearseattle.com" },
  { name: "Ocean Grove", website: "https://oceangrove.com" },
  { name: "Deadlights", website: "https://deadlights.bandcamp.com" },
  { name: "Earth Caller", website: "https://earthcaller.com.au" },
  { name: "Alpha", website: "https://alphaband.com" },
  { name: "Future Static", website: "https://futurestaticband.com" },
  { name: "Harbours", website: "https://harbours.bandcamp.com" },
  { name: "Lune", website: "https://luneband.com" }
  { name: "Thornhill", website: "https://thornhill.band" },
  { name: "Yours Truly", website: "https://yourstrulyband.com" },
  { name: "Endless Heights", website: "https://endlessheights.com" },
  { name: "Pagan", website: "https://paganspace.com" },
  { name: "Hellions", website: "https://hellions.bandcamp.com" },
  { name: "Alpha Wolf", website: "https://alphawolf.com.au" },
  { name: "Justice for the Damned", website: "https://justiceforthedamned.com" },
  { name: "Make Them Suffer", website: "https://makethemsuffer.com.au" },
  { name: "Hands Like Houses", website: "https://handslikehouses.net" },
  { name: "The Beautiful Monument", website: "https://thebeautifulmonument.bandcamp.com" },
  { name: "Gravemind", website: "https://gravemindband.com" },
  { name: "Slowly Slowly", website: "https://slowlyslowlyband.com" },
  { name: "Alpha", website: "https://alphaband.com" },
  { name: "Windwaker", website: "https://windwakerband.com" },
  { name: "Deadlights", website: "https://deadlights.bandcamp.com" },
  { name: "Void of Vision", website: "https://voidofvision.com" },
  { name: "Earth Caller", website: "https://earthcaller.com.au" },
  { name: "Belle Haven", website: "https://bellehaven.com" },
  { name: "Harbours", website: "https://harbours.bandcamp.com" },
  { name: "Reside", website: "https://reside.band" },
  { name: "Lune", website: "https://luneband.com" },
  { name: "Mirrors", website: "https://mirrorsband.com" },
  { name: "Bloom", website: "https://bloomhc.com" },
  { name: "Statues", website: "https://statuesband.com" },
  { name: "Weighbridge", website: "https://weighbridge.bandcamp.com" },
  { name: "Future Static", website: "https://futurestaticband.com" },
  { name: "Relapse", website: "https://relapseband.com" },
  { name: "Shinto Katana", website: "https://shintokatana.com" },
  { name: "Dream State Empire", website: "https://dreamstateempire.bandcamp.com" },
  { name: "Gravemind", website: "https://gravemind.bandcamp.com" },
  { name: "Polaris", website: "https://polarisaus.com" },
  { name: "Northlane", website: "https://northlaneband.com" },
  { name: "In Hearts Wake", website: "https://inheartswake.com" },
  { name: "Ocean Grove", website: "https://oceangrove.com" },
  { name: "Tired Lion", website: "https://tiredlion.band" },
  { name: "Dear Seattle", website: "https://dearseattle.com" },
  { name: "RedHook", website: "https://redhookofficial.com" },
  { name: "Kingswood", website: "https://kingswoodband.com" },
  { name: "Ne Obliviscaris", website: "https://neobliviscaris.com" },
  { name: "Plini", website: "https://plini.co" },
  { name: "Caligula's Horse", website: "https://caligulashorse.com" },
  { name: "Karnivool", website: "https://karnivool.com.au" },
  { name: "Circles", website: "https://circles.band" },
  { name: "The Ocean", website: "https://theocean.bandcamp.com" },
  { name: "Twelve Foot Ninja", website: "https://twelvefootninja.com" },
  { name: "Dead Letter Circus", website: "https://deadlettercircus.com" },
  { name: "Meniscus", website: "https://meniscus.bandcamp.com" },
  { name: "Sleepmakeswaves", website: "https://sleepmakeswaves.com" },
  { name: "Helm", website: "https://helmband.com" },
  { name: "Closure in Moscow", website: "https://closureinmoscow.com" },
  
];

module.exports = bandsList;
